### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Reza-Fahlevi** [saamodra/sneemo2021#1]
Maaf pak ini cara menggunakan aplikasinya bagaimana ya? Saya sudah clone tapi masih bingung ingin menjalankan aplikasinya

**Comment by saamodra** [comment]
Buka file `index.html` pak

**Comment by Reza-Fahlevi** [comment]
Oke pak saya coba dulu ya
![image](https://user-images.githubusercontent.com/33341301/129490171-b2da1582-1f17-4f46-a75e-e79b91c814b6.png)
